### ISSUE TITLE
Misleading comment in SHACL

### ISSUE THREAD

**Issue by rgabbard** [NextCenturyCorporation/AIDA-Interchange-Format#114]
[The SHACL file](https://github.com/NextCenturyCorporation/AIDA-Interchange-Format/blob/master/src/main/resources/com/ncc/aif/aida_ontology.shacl) has:

```
aida:CompoundJustificationShape
   a sh:NodeShape ;
   sh:targetClass aida:CompoundJustification ;

   # must have at least two contained justifications
   sh:property [
     sh:path aida:containedJustification ;
     sh:xone (
       [sh:class aida:TextJustification]
       [sh:class aida:ImageJustification]
       [sh:class aida:AudioJustification]
       [sh:class aida:KeyFrameVideoJustification]
       [sh:class aida:ShotVideoJustification] ) ;
     sh:minCount 1 ] ;

   # justification must provide confidence
   sh:property aida:RequiredConfidencePropertyShape ;

   # may provide an optional source system
   sh:property aida:SystemPropertyShape .
```

So the `aida:containedJustification` property, `sh:minCount 1`, so the comment `# must have at least two contained justifications` is incorrect (and I believe NIST sometimes uses `CompoundJustifications` which are not in fact "compound" :-) )

**Comment by nextcen-dgemoets** [comment]
It looks like the minCount was changed from 2 to 1 but the comment wasn't updated.

**Comment by ecurley-nextcentury** [comment]
Aida 287 put back the minimum of 2. Closing.
