### ISSUE TITLE
Interchange ontology lacks aida:informativeJustification

### ISSUE THREAD

**Issue by rgabbard** [NextCenturyCorporation/AIDA-Interchange-Format#184]

**Comment by craigwarsaw** [comment]
Thanks for raising this @rgabbard. Added as internal ticket AIDA-793 to our next sprint.

**Comment by nextcen-dgemoets** [comment]
This has been fixed and is part of [AIF 1.0.0](https://github.com/NextCenturyCorporation/AIDA-Interchange-Format/releases/tag/v1.0.0).
