### ISSUE TITLE
Add NAMESPACE constant to AidaDomainOntologiesCommon

### ISSUE THREAD

**Issue by gabbard** [NextCenturyCorporation/AIDA-Interchange-Format#198]
It is handy to use as a prefix when users are writing their own SPARQL queries in code.  A similar namespace constant is already present in `AidaAnnotationOntology`.

**Comment by nextcen-dgemoets** [comment]
Hi, Ryan.  I took a look and unlike `AidaAnnotationOntology`, `AidaDomainOntologiesCommon` is a generated file, created generically by the `OntologyGeneration` class.  We'd have to introduce/hack some special-case code into the generator to add this prefix.  Or we'd have to add the prefix "manually" and make sure we add it back again every time the file is generated.

Still, I'll write a ticket to address it.

**Comment by ecurley-nextcentury** [comment]
Fixing in #282

**Comment by ecurley-nextcentury** [comment]
Fixed in #282
