### ISSUE TITLE
Use DatatypeProperty rather than DataTypeProperty

### ISSUE THREAD

**Issue by cedorman** [NextCenturyCorporation/AIDA-Interchange-Format#77]
owl:DataTypeProperty is doesn't exist; it is owl:DatatypeProperty.  Ontology tools that are not case-sensitive do not throw an error, but case-sensitive ones do.

**Comment by nextcen-dgemoets** [comment]
None of our ontology files still say `owl:DataTypeProperty`.  Closing issue.
